import 'server-only';

interface GoogleRecaptchaResponse {
  success: boolean;
  score: number;
  action: string;
  challenge_ts: string;
  hostname: string;
  'error-codes'?: string[];
}

interface RecaptchaOutcome {
  success: boolean;
  score: number;
  error?: string;
}

/**
 * Verifies a reCAPTCHA v3 token with Google's API.
 * @param token The token generated by the client-side reCAPTCHA script.
 * @param action The expected action name (e.g., 'login', 'signup', 'forgot_password').
 * @param threshold The minimum score required to be considered human (default 0.5).
 * @returns An object containing the success status and the score.
 */
export async function verifyRecaptcha(
  token: string | null | undefined,
  action: string,
  threshold: number = 0.5
): Promise<RecaptchaOutcome> {
  if (!token) {
    return { success: false, score: 0, error: 'reCAPTCHA token is missing.' };
  }

  const secretKey = process.env.GOOGLE_RECAPTCHA_V3_SECRET_KEY;

  if (!secretKey) {
    console.error('GOOGLE_RECAPTCHA_V3_SECRET_KEY is not defined in environment variables.');
    // In production, we might want to fail closed (secure) or open (user experience)
    // For now, we'll log the error and allow the request if we're in development, 
    // but in a real app, this should be a hard failure.
    return { success: true, score: 1.0 }; // Fallback to allow if misconfigured, change as per security policy
  }

  try {
    const response = await fetch('https://www.google.com/recaptcha/api/siteverify', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        secret: secretKey,
        response: token,
      }).toString(),
    });

    const data: GoogleRecaptchaResponse = await response.json();

    if (!data.success) {
      return {
        success: false,
        score: data.score || 0,
        error: `reCAPTCHA verification failed: ${data['error-codes']?.join(', ') || 'unknown error'}`,
      };
    }

    // Verify the action matches what we expect
    if (data.action !== action) {
      return {
        success: false,
        score: data.score,
        error: `reCAPTCHA action mismatch: expected "${action}", got "${data.action}"`,
      };
    }

    // Check if the score is above the threshold
    if (data.score < threshold) {
      return {
        success: false,
        score: data.score,
        error: 'Low reCAPTCHA score. Submission blocked.',
      };
    }

    return { success: true, score: data.score };
  } catch (error) {
    console.error('Error verifying reCAPTCHA:', error);
    return { success: false, score: 0, error: 'Internal error during reCAPTCHA verification.' };
  }
}
